export const USER_ROLE_ADMIN = 'ADMIN'
export const USER_ROLE_OPERATOR = 'OPERATOR'
export const USER_ROLE_VIEWER = 'VIEWER'

export const TRANSACTION_TYPE_DEBIT = 1;
export const TRANSACTION_TYPE_KREDIT = -1;

export const VALIDATION_MAX_FILE_SIZE = 1024 * 1024 * 5; // 5 MB
export const VALIDATION_ALLOWED_FILE_TYPE = ['image/jpg', 'image/jpeg', 'image/png', 'image/webp'];

export const STOCKMOVEMENTVEHICLE_TYPE_TRANSFER = "TRANSFER"
export const STOCKMOVEMENTVEHICLE_TYPE_IN = "IN"
export const STOCKMOVEMENTVEHICLE_TYPE_PURCHASE_ORDER = "PURCHASE_ORDER"
export const STOCKMOVEMENTVEHICLE_TYPE_RETAIL = "RETAIL"

export const STOCKMOVEMENTVEHICLE_STATUS_LOADING = "LOADING"
export const STOCKMOVEMENTVEHICLE_STATUS_IN_TRANSIT = "IN_TRANSIT"
export const STOCKMOVEMENTVEHICLE_STATUS_UNLOADING = "UNLOADING"
export const STOCKMOVEMENTVEHICLE_STATUS_COMPLETED = "COMPLETED"

export const STOCKMOVEMENTVEHICLE_TYPES = [
  {
    label: "TRANSFER",
    value: STOCKMOVEMENTVEHICLE_TYPE_TRANSFER
  },
  {
    label: "STOCK IN",
    value: STOCKMOVEMENTVEHICLE_TYPE_IN
  },
  {
    label: "PURCHASE ORDER",
    value: STOCKMOVEMENTVEHICLE_TYPE_PURCHASE_ORDER
  },
  {
    label: "RETAIL",
    value: STOCKMOVEMENTVEHICLE_TYPE_RETAIL
  }
]


export const STOCKMOVEMENTVEHICLE_STATUSES = [
  {
    label: "LOADING",
    value: STOCKMOVEMENTVEHICLE_STATUS_LOADING
  },
  {
    label: "IN TRANSIT",
    value: STOCKMOVEMENTVEHICLE_STATUS_IN_TRANSIT
  },
  {
    label: "UNLOADING",
    value: STOCKMOVEMENTVEHICLE_STATUS_UNLOADING
  },
  {
    label: "COMPLETED",
    value: STOCKMOVEMENTVEHICLE_STATUS_COMPLETED
  }
]